### ISSUE TITLE
introduction/learning.md の翻訳

### ISSUE THREAD

**Issue by koga1020** [fukuoka-ex/phoenix-guide-ja#15]
## 対応について
対応してくださる方はAssigneesにご自身のアカウントの設定をお願いします🙇

**Comment by TORIFUKUKaiou** [comment]
@koga1020 
まずは手始めにこの辺から担当したいとおもっています。
感じをつかんでバリバリプルリクしたいとおもっています！

Assigneesの変更ってのがわかりませんでした。
ちなみにこんな感じ↓↓↓ で私のアカウントではみえています。

<img width="1072" alt="スクリーンショット 2020-03-15 11 33 47" src="https://user-images.githubusercontent.com/4215723/76694043-0e193900-66b1-11ea-9f4e-033420271541.png">

たとえば、https://seleck.cc/647 のページの説明ですと、歯車アイコンがついていたりするのですが私には見えていないので権限が足りない等があるのかなあとかおもっています。
お手数おかけしますがご確認よろしくお願いします 🙇

**Comment by koga1020** [comment]
✅
